version: '3.8'
services:
  postgres:
    image: postgres:14.9
    container_name: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    name: app-network  # Optional but explicit
    driver: bridge