openapi: 3.0.0
info:
  title: User Clubs & Events API
  version: 1.0.0
  description: API to retrieve events and analytics for users based on their club memberships.

paths:
  /api/users/{userId}/events:
    get:
      summary: Get all events for a user
      description: Returns all events the user is associated with via club memberships.
      tags:
        - Events
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
          description: UUID of the user
      responses:
        "200":
          description: List of events the user is associated with
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEventSummary"
        "404":
          description: User not found
        "500":
          description: Internal server error

  /api/clubs/analytic/{userId}:
    get:
      summary: Get analytics for all clubs a user belongs to
      description: Retrieve attendance and task analytics for each club associated with a user.
      tags:
        - ClubAnalytics
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
          description: The user ID to fetch analytics for
      responses:
        "200":
          description: Analytics for all clubs the user is a member of
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserClubAnalytics"
              examples:
                exampleResponse:
                  summary: Example response with two clubs
                  value:
                    - clubId: "f1a6c8fd-4c2f-4f8d-91f2-6d0b2c1a7e91"
                      clubName: "Photography Society"
                      attendanceThisMonth: 42
                      monthlyAverage: 100
                      tasks:
                        completed: 12
                        overdue: 3
                        ongoing: 5
                      attendanceLast12Months:
                        - month: "10/2024"
                          value: 30
                        - month: "11/2024"
                          value: 25
                        - month: "12/2024"
                          value: 40
                    - clubId: "c7b2d9ad-52d3-44f5-a3d0-23a8c6bcd921"
                      clubName: "Debating Club"
                      attendanceThisMonth: 18
                      tasks:
                        completed: 5
                        overdue: 2
                        ongoing: 7
                      attendanceLast12Months:
                        - month: "10/2024"
                          value: 10
                        - month: "11/2024"
                          value: 15
                        - month: "12/2024"
                          value: 18
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Missing required parameter: userId"
        "404":
          description: User not found or no clubs associated
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "User not found or no clubs associated"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Internal server error"

components:
  schemas:
    UserClubAnalytics:
      type: object
      properties:
        clubId:
          type: string
          format: uuid
        clubName:
          type: string
        attendanceThisMonth:
          type: integer
          description: Number of people who attended events this month
        monthlyAverage:
          type: integer
          description: Average number of people attending per month
        tasks:
          type: object
          properties:
            completed:
              type: integer
            overdue:
              type: integer
            ongoing:
              type: integer
          required:
            - completed
            - overdue
            - ongoing
        attendanceLast12Months:
          type: array
          description: Monthly attendance counts for the past 12 months
          items:
            type: object
            properties:
              month:
                type: string
                pattern: "^(0[1-9]|1[0-2])/\\d{4}$"
              value:
                type: integer
            required:
              - month
              - value
      required:
        - clubId
        - clubName
        - attendanceThisMonth
        - tasks
        - attendanceLast12Months

    UserEventSummary:
      type: object
      properties:
        eventId:
          type: string
          format: uuid
        title:
          type: string
      required:
        - eventId
        - title
