openapi: 3.0.0
info:
  title: User Events API
  version: 1.0.0
  description: API to retrieve events associated with a user based on their club memberships.

paths:
  /api/users/{userId}/events:
    get:
      summary: Get all events for a user
      description: Returns all events the user is associated with via club memberships.
      tags:
        - Events
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
          description: UUID of the user
      responses:
        "200":
          description: List of events the user is associated with
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserEventSummary"
        "404":
          description: User not found
        "500":
          description: Internal server error

  /api/clubs/analytics:
    get:
      summary: Get analytics for one or more clubs
      description: Retrieve attendance and upcoming task analytics for one or more clubs.
      tags:
        - ClubAnalytics
      parameters:
        - in: query
          name: clubId
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
          style: form
          explode: true
          description: List of club IDs (repeat the parameter for multiple, e.g. clubId=...&clubId=...)
        - in: query
          name: startDate
          required: false
          schema:
            type: string
            format: date-time
          description: Start date for filtering attendanceAveragePoints (inclusive)
        - in: query
          name: endDate
          required: false
          schema:
            type: string
            format: date-time
          description: End date for filtering attendanceAveragePoints (inclusive)
      responses:
        "200":
          description: Analytics for the requested clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClubAnalytics"
              examples:
                twoClubsExample:
                  summary: Two clubs, one with and one without an upcoming event
                  value:
                    - clubId: "abcd1234-1111-2222-3333-444455556666"
                      attendanceAveragePoints:
                        - time: "2025-09-20T09:00:00Z"
                          value: 63
                        - time: "2025-09-23T09:00:00Z"
                          value: 44
                      attendanceAverageYTD: 45
                      upcomingTask:
                        activityId: "b1a6f8fd-4c2f-4f8d-91f2-6d0b2c1a7e90"
                        activityTitle: "Committee Planning Session"
                        startTime: "2025-09-20T09:00:00Z"
                        endTime: "2025-09-20T10:30:00Z"
                        dependsOnEventId: "5e0c1c77-9a4e-4c2e-9f41-2b3a5f8d6b0a"
                        completionPercentage: 85
                    - clubId: "efgh5678-7777-8888-9999-000011112222"
                      attendanceAveragePoints: []
                      attendanceAverageYTD: 0
                      upcomingTask: null
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Missing required parameter: clubId"
        "404":
          description: Club not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "One or more clubs not found"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Internal server error"

components:
  schemas:
    UserEventSummary:
      type: object
      properties:
        eventId:
          type: string
          format: uuid
        title:
          type: string
      required:
        - eventId
        - title

    ClubAnalytics:
      type: object
      properties:
        clubId:
          type: string
          format: uuid
        attendanceAveragePoints:
          type: array
          items:
            $ref: "#/components/schemas/AttendancePoint"
        attendanceAverageYTD:
          type: integer
        upcomingTask:
          oneOf:
            - $ref: "#/components/schemas/UpcomingTask"
            - type: "null"
      required:
        - clubId
        - attendanceAveragePoints
        - attendanceAverageYTD
        - upcomingTask

    AttendancePoint:
      type: object
      properties:
        time:
          type: string
          format: date-time
        value:
          type: integer
      required:
        - time
        - value

    UpcomingTask:
      type: object
      properties:
        activityId:
          type: string
          format: uuid
        activityTitle:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        dependsOnEventId:
          type: string
          format: uuid
        completionPercentage:
          type: integer
      required:
        - activityId
        - activityTitle
        - startTime
        - endTime
        - dependsOnEventId
        - completionPercentage
