openapi: 3.0.0
info:
  title: SigmaSchedule API
  version: 1.0.0
paths:
  /api/auth:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - firstname
                - lastname
                - email
                - password
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
        '400':
          description: Invalid input

  /api/auth/login:
    post:
      summary: Sign in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '202':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string

        '404':
          description: user not found
  /api/clubs:
    post:
      summary: Create a new club
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
                - description
      responses:
        '200':
          description: Club created
          content:
            application/json:
              schema:
                type: object
                properties:
                  clubId:
                    type: string
        '400':
          description: Invalid club data
  /api/clubs/users:
    post:
      summary: Add a user to a club
      parameters:
        - in: path
          name: clubId
          required: true
          schema:
            type: string
          description: UUID of the club
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clubId:
                  type: string
                  format: uuid
                userId:
                  type: string
                  format: uuid
                role:
                  type: string
                  enum: [ admin, member ]
              required:
                - userId
                - role
      responses:
        '204':
          description: User added to club
  /api/clubs/{clubId}/invite:
    post:
      summary: Invite a user to a club
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                clubId:
                  type: string
                role:
                  type: string
                  enum: [ admin, member ]
              required:
                - email
                - clubId
                - role
      responses:
        '204':
          description: Invitation sent
        '404':
          description: Club not found

