spring:
  datasource:
    url: jdbc:postgresql://terraform-20250713130815526900000003.cfae22e00nfp.ap-southeast-2.rds.amazonaws.com:5432/capstonedb
    username: capstone_admin
    password: Mishfish123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
  mail:
    host: email-smtp.ap-southeast-2.amazonaws.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt-secret: ${JWT_SECRET}