spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration