spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  mail:
    host: smtp
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
app:
  jwt-secret: 7WZgM8lrfzEp9yJVFqAD3vUMRxKzP5tCBwqYxLZd5Tk=

qr:
  endpoint: "http://localhost:5173/attendance"

invite:
  endpoint: "http://localhost:5173/register?token="